version: '3.1'
services:
  #################################
  #  Main app container           #
  #################################
  main-service:
    ports:
    - "8080:80"
    - "443:443"
    - "20-21:20-21"
    - "21100-21110:21100-21110"
    volumes:
    - "../../../packages:/srv/packages"

  #################################
  #  Database container           #
  #################################
  mysql:
      image: mysql:5.7
      container_name: "${APP_NAME}_mysql"
      ports:
        - "9093:3306"
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: homestead
        MYSQL_USER: homestead
        MYSQL_PASSWORD: secret
      volumes:
        -  "../../.service-main/.mysql:/var/lib/mysql"
