version: '3.1'
services:
  #################################
  #  Main app container           #
  #################################
  main-service:
    ports:
    - "80:80"
    - "443:443"
    - "20-21:20-21"
    - "21100-21110:21100-21110"
